/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.Assessmetric();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Assessmetric', function() {
    it('should create an instance of Assessmetric', function() {
      // uncomment below and update the code to test Assessmetric
      //var instane = new TempApi.Assessmetric();
      //expect(instance).to.be.a(TempApi.Assessmetric);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property bmi (base name: "bmi")', function() {
      // uncomment below and update the code to test the property bmi
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property waistcirc (base name: "waistcirc")', function() {
      // uncomment below and update the code to test the property waistcirc
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property oximetry (base name: "oximetry")', function() {
      // uncomment below and update the code to test the property oximetry
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property proteinintake (base name: "proteinintake")', function() {
      // uncomment below and update the code to test the property proteinintake
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property systolic (base name: "systolic")', function() {
      // uncomment below and update the code to test the property systolic
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property diastolic (base name: "diastolic")', function() {
      // uncomment below and update the code to test the property diastolic
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property grainintake (base name: "grainintake")', function() {
      // uncomment below and update the code to test the property grainintake
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property fruitintake (base name: "fruitintake")', function() {
      // uncomment below and update the code to test the property fruitintake
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

    it('should have the property vegintake (base name: "vegintake")', function() {
      // uncomment below and update the code to test the property vegintake
      //var instance = new TempApi.Assessmetric();
      //expect(instance).to.be();
    });

  });

}));
